package View.Seller;

public enum SellerMenuOptions {
    VIEW_PRODUCTS,ADD_PRODUCTS,REMOVE_PRODUCTS,SEARCH_PRODUCTS,VIEW_ORDERS,CHECK_STOCK,VIEW_PROFILE,UPDATE_PROFILE,REMOVE_CUSTOMER_ACCOUNT,LOGOUT,DEFAULT
}
